apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-fybt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-fybt
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-fybt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-fybt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-fybt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-awyn-tenant/rhtap-demo-app/hacbs-test-project-fybt@sha256:7209c8405b06b7ee7d053839bce1b300139ed2bfa88122f370c9a7f6513f4af5
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
